export const Currencies = [
    {value: "usd", label: "$ USD" , locale: "en-US"},
    {value: "eur", label: "€ Euro" , locale: "de-DE"},
    {value: "gbp", label: "£ Pound" , locale: "en-GB"},
    {value: "jpy", label: "¥ Yen" , locale: "ja-JP"},
    {value: "cad", label: "$ Canadian Dollar" , locale: "en-CA"},
    {value: "aud", label: "$ Australian Dollar" , locale: "en-AU"},
    {value: "nzd", label: "$ New Zealand Dollar" , locale: "en-NZ"},
    {value: "chf", label: "Fr Swiss Franc" , locale: "de-CH"},
    {value: "sek", label: "kr Swedish Krona" , locale: "sv-SE"},
    {value: "nok", label: "kr Norwegian Krone" , locale: "no-NO"},
    {value: "dkk", label: "kr Danish Krone" , locale: "da-DK"},
    {value: "rub", label: "₽ Russian Ruble" , locale: "ru-RU"},
    {value: "cny", label: "¥ Chinese Yuan" , locale: "zh-CN"},
    {value: "inr", label: "₹ Indian Rupee" , locale: "hi-IN"},
    {value: "brl", label: "R$ Brazilian Real" , locale: "pt-BR"},
    {value: "zar", label: "R South African Rand" , locale: "en-ZA"},
    {value: "hkd", label: "$ Hong Kong Dollar" , locale: "zh-HK"},
    {value: "sgd", label: "$ Singapore Dollar" , locale: "en-SG"},
    {value: "idr", label: "Rp Indonesian Rupiah" , locale: "id-ID"},
    {value: "krw", label: "₩ South Korean Won" , locale: "ko-KR"},
    {value: "mxn", label: "$ Mexican Peso" , locale: "es-MX"},
    {value: "myr", label: "RM Malaysian Ringgit" , locale: "ms-MY"},
    {value: "php", label: "₱ Philippine Peso" , locale: "fil-PH"},
    {value: "thb", label: "฿ Thai Baht" , locale: "th-TH"},
    {value: "try", label: "₺ Turkish Lira" , locale: "tr-TR"},
    {value: "aed", label: "د.إ United Arab Emirates Dirham" , locale: "ar-AE"},
    {value: "vnd", label: "₫ Vietnamese Dong" , locale: "vi-VN"},
    {value: "pln", label: "zł Polish Zloty" , locale: "pl-PL"},
    {value: "czk", label: "Kč Czech Koruna" , locale: "cs-CZ"},
    {value: "huf", label: "Ft Hungarian Forint" , locale: "hu-HU"},
    {value: "ils", label: "₪ Israeli Shekel" , locale: "he-IL"},
    {value: "clp", label: "$ Chilean Peso" , locale: "es-CL"},
    {value: "cop", label: "$ Colombian Peso" , locale: "es-CO"},
    {value: "egp", label: "E£ Egyptian Pound" , locale: "ar-EG"},
    {value: "kwd", label: "د.ك Kuwaiti Dinar" , locale: "ar-KW"},
    {value: "sar", label: "ر.س Saudi Riyal" , locale: "ar-SA"},
    {value: "pen", label: "S/ Peruvian Sol" , locale: "es-PE"},
    {value: "qar", label: "ر.ق Qatari Riyal" , locale: "ar-QA"},


]
export type Currency = (typeof Currencies)[0]